### ISSUE TITLE
Video Search Feature

### ISSUE THREAD

**Issue by alacritythief** [alacritythief/YangSearch#4]
### Video Search Feature

**[Part of v0.2 milestone](https://github.com/alacritythief/YangSearch/milestone/2)**

Similar to policy search, there will be a video.js file in the `lib` directory that contains a JavaScript object full of relevant videos, topic timestamps, and keywords relevant to those timestamps.

There will be a videosearch.js file in the `lib` directory that will contain the search function, utilizing Fuse.js to search relevant keywords and titles. It will be built similarly to `policysearch.js`.

### What's Needed:
* Options on the search bar to search policies, media, or both.
* A video results list component based on the App's main search input, which contains a thumbnail and relevant topic timestamp.
* A separate individual video page and route so you can interface with the video player and topic list.
* Video player component, supports Youtube at first but will be expanded to other platforms over time depending on API and external support.
* A topic list component populated with topic items that list timestamps and a topic summary. Makes the video player jump to a timestamp when an item on the list is clicked.

**Comment by rak5381** [comment]
I don't know if this is helpful, but it seemed worth bringing to your attention. Found on reddit: https://docs.google.com/spreadsheets/d/1rzslAZJUussOGaewRYsPalM9Y_2JJbfWtJ252SlzktI/edit#gid=265140854

**Comment by alacritythief** [comment]
@rak5381 Thanks, this is really helpful! I'll add this to our internal list of resources. 👍

**Comment by alacritythief** [comment]
Closing this as the video feature is not a priority and I am working on other Yang related projects for the volunteer tech team.
